### ISSUE TITLE
Progress Checklist

### ISSUE THREAD

**Issue by johnbarrierwilson** [northlandchurch/Website-Styles#4]
This is just a running list (in alphabetical order) of items that have been completed, and that need to be completed. It will continue to grow as the project progresses, but basically exists just to be organized. Feel free to have more discussion below if something isn't necessary, something is missing, or you would like to know what something is referring to.
## Pages & Other Templates

These are made up from individual styles listed above. These will most likely be checked off much later than the individual styles, and closer to the end of the project, but they are here nonetheless.
- [x] About
- [x] Calendar: Single Event
- [x] Calendar: List
- [x] Calendar: Mini
- [x] Connect
- [ ] Distributed Church
- [x] Homepage
- [x] Live Worship
- [x] Ministires
- [x] Ministry
- [x] Need Help?
- [x] Resource: Article
- [x] Resource: Liturgy
- [x] Resource: Need
- [ ] Resource: Prayer
- [x] Resource: Video
- [x] Resources
- [x] Search
- [x] Team: Individual
- [x] Team: Grid
- [x] Tithe
## Individual Styles
- [x] Breadcrumbs
- [x] Button: Standard
- [x] Button: Transparent
- [x] Cell: Small
- [x] Cell: Standard
- [x] Deck: Filter
- [x] Deck: Inverted
- [x] Deck: Standard
- [x] Download: Resource
- [x] Download: Video
- [x] Editorial: Imageless
- [x] Editorial: Size Featured
- [x] Editorial: Size Large
- [x] Grid
- [x] Heading: Extra Large
- [x] Heading: Italic
- [x] Heading: Large
- [x] Heading: Small
- [x] Hero: Live
- [x] Hero: Primary
- [x] Hero: Secondary
- [x] Hero: Resource_s_
- [x] Hero: Resource
- [x] Inputs
- [x] Logo
- [x] Media: Large
- [x] Media: Medium
- [x] Media: w/ text (refactor from Editorial flush and and short)
- [x] Navigation
- [x] Rows
- [x] Rule: Resources
- [x] Rule: Story
- [x] Rule: Transparent
- [x] Tag (for resources)

**Comment by jhnwlsn** [comment]
@chadturnbull – Assigning you a to-do: if you could get together some actual content to put in for the Distributed Church page, that would be helpful as it is a little more custom than the other pages. This way, I'll make sure that it supports exactly what you all want to promote on that page. ;)
